---
header:
  - license:
      spdx-id: Apache-2.0
      copyright-owner: kdoctor-io
      pattern: |
        Copyright|Apache-2.0
      content: |
        Copyright 2023 Authors of kdoctor-io
        SPDX-License-Identifier: Apache-2.0
    paths:
      - '**/*.go'
      - '**/*.sh'
    paths-ignore:
      - 'vendor'
      - 'pkg/k8s'
      - 'api'
    comment: on-failure
